version: '3.8'

services:
    dev:
        container_name: solomon-api
        image: punparin/solomon-api:local
        env_file:
            - .env
        volumes:
            - ./config.json:/app/config.json
        ports:
            - 8080:8080
        restart: unless-stopped
    redis:
        image: redis:7.0.0
        command: redis-server --requirepass password
        container_name: redis
        ports:
            - 6379:6379
